# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Amos-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 527)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Box_Stadt = QtWidgets.QComboBox(self.centralwidget)
        self.Box_Stadt.setGeometry(QtCore.QRect(10, 10, 181, 51))
        self.Box_Stadt.setObjectName("Box_Stadt")
        self.Box_Stadt.addItem("")
        self.Box_Stadt.addItem("")
        self.Button_Detection = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Detection.setGeometry(QtCore.QRect(430, 400, 141, 51))
        self.Button_Detection.setObjectName("Button_Detection")
        self.Button_Bild = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Bild.setGeometry(QtCore.QRect(50, 400, 161, 51))
        self.Button_Bild.setObjectName("Button_Bild")
        self.Label_Bild = QtWidgets.QLabel(self.centralwidget)
        self.Label_Bild.setGeometry(QtCore.QRect(20, 110, 621, 271))
        self.Label_Bild.setText("")
        self.Label_Bild.setPixmap(QtGui.QPixmap("Fernsehturm.jpg"))
        self.Label_Bild.setScaledContents(True)
        self.Label_Bild.setObjectName("Label_Bild")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Box_Stadt.activated.connect(self.show_popup)
        self.Button_Detection.clicked.connect(self.start_detection)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SightScan"))
        self.Box_Stadt.setItemText(0, _translate("MainWindow", "Choose City"))
        self.Box_Stadt.setItemText(1, _translate("MainWindow", "Berlin"))
        self.Button_Detection.setText(_translate("MainWindow", "Start Detection"))
        self.Button_Bild.setText(_translate("MainWindow", "Load Image"))

    def show_popup(self):
        if self.Box_Stadt.currentIndex() > 0:
            msg = QMessageBox()
            msg.setWindowTitle("Download City")
            msg.setText("Do you want to download " + self.Box_Stadt.currentText() + "?")
            msg.setIcon(QMessageBox.Question)
            msg.setStandardButtons(QMessageBox.Cancel|QMessageBox.Ok)
            msg.setDefaultButton(QMessageBox.Ok)
            msg.setInformativeText("When downloaded sights of " + self.Box_Stadt.currentText() + " can be detected.")

            msg.buttonClicked.connect(self.handover_city)

            x = msg.exec_()

    def handover_city(self, i):
        if i.text() == "OK":
            city = self.Box_Stadt.currentText()

    def start_detection (self):
        
           


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
