# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Amos-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class UI_MainWindow(QWidget):
    image_name = "background.jpg"

    def setupUI(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 527)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Box_Stadt = QComboBox(self.centralwidget)
        self.Box_Stadt.setGeometry(QtCore.QRect(10, 10, 181, 51))
        self.Box_Stadt.setObjectName("Box_Stadt")
        self.Box_Stadt.addItem("")
        self.Box_Stadt.addItem("")
        self.Box_Stadt.activated.connect(self.show_popup)

        self.Button_Detection = QPushButton(self.centralwidget)
        self.Button_Detection.setGeometry(QtCore.QRect(430, 400, 141, 51))
        self.Button_Detection.setObjectName("Button_Detection")
        self.Button_Detection.clicked.connect(self.start_detection)

        self.Button_Bild = QPushButton(self.centralwidget)
        self.Button_Bild.setGeometry(QtCore.QRect(50, 400, 161, 51))
        self.Button_Bild.setObjectName("Button_Bild")
        self.Button_Bild.clicked.connect(self.dragdrop)

        self.Label_Bild = QLabel(self.centralwidget)
        self.Label_Bild.setGeometry(QtCore.QRect(20, 110, 621, 271))
        self.Label_Bild.setText("")
        self.Label_Bild.setPixmap(QPixmap("background.jpg"))
        self.Label_Bild.setScaledContents(True)
        self.Label_Bild.setObjectName("Label_Bild")
        self.Label_Bild.setAlignment(Qt.AlignCenter)
        self.Label_Bild.setAcceptDrops(True)

        self.setAcceptDrops(True)
        self.Main_Layout = QVBoxLayout(self.Label_Bild)
        self.Main_Layout.addWidget(self.Label_Bild)
        self.setLayout(self.Main_Layout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SightScan"))
        self.Box_Stadt.setItemText(0, _translate("MainWindow", "Choose City"))
        self.Box_Stadt.setItemText(1, _translate("MainWindow", "Berlin"))
        self.Button_Detection.setText(_translate("MainWindow", "Start Detection"))
        self.Button_Bild.setText(_translate("MainWindow", "Enable File Drop"))

    def show_popup(self):
        if self.Box_Stadt.currentIndex() > 0:
            msg = QMessageBox()
            msg.setWindowTitle("Download City")
            msg.setText("Do you want to download " + self.Box_Stadt.currentText() + "?")
            msg.setIcon(QMessageBox.Question)
            msg.setStandardButtons(QMessageBox.Cancel|QMessageBox.Ok)
            msg.setDefaultButton(QMessageBox.Ok)
            msg.setInformativeText("When downloaded sights of " + self.Box_Stadt.currentText() + " can be detected.")

            msg.buttonClicked.connect(self.handover_city)

            x = msg.exec_()

    def handover_city(self, i):
        if i.text() == "OK":
            city = self.Box_Stadt.currentText()

    def start_detection (self):
        print('start detection of ' + self.image_name)
        #start detection with image_name

    def dragdrop(self):
        if(self.Button_Bild.text() == "Enable File Drop"):
            self.Label_Bild.setAcceptDrops(True)
            self.Label_Bild.setText('\n\n Drop Image here \n\n')
            self.Label_Bild.setStyleSheet('''
                QLabel{
                    border: 4px dashed 
                }
            ''')
            self.Button_Bild.setText(QCoreApplication.translate("MainWindow", "Disable File Drop"))
        elif(self.Button_Bild.text() == "Disable File Drop"):
            self.Label_Bild.setAcceptDrops(False)
            self.Label_Bild.setText("")
            self.Label_Bild.setStyleSheet('')
            self.Label_Bild.setPixmap(QPixmap("background.jpg"))
            self.Button_Bild.setText(QCoreApplication.translate("MainWindow", "Enable File Drop"))

    def dragEnterEvent(self, event):
        print('dragEnter')
        if event.mimeData().hasFormat('image/*'):
            event.accept()
        else:
            event.ignore()

    def dragMoveEvent(self, event):
        print('dragMove')
        if event.mimeData().hasFormat('image/*'):
            event.accept()
        else:
            event.ignore()

    def dropEvent(self, event):
        print('drop')
        if event.mimeData().hasFormat('image/*'):
            print('drop event')
            event.setDropAction(Qt.CopyAction)
            self.image_name = event.mimeData().urls()[0].toLocalFile()
            self.Label_Bild.setPixmap(QPixmap(self.image))

            event.accept()
        else:
            event.ignore()

if __name__ == "__main__":
    import sys, os
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = UI_MainWindow()
    ui.setupUI(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
